---
- hosts: dev
  become: yes
  tasks:
  # FIXME: this isn't working right...
  # - name: add gcloud apt-key
  #   apt_key:
  #     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  #     state: present
  # - name: add gcloud apt repository
  #   apt_repository:
  #     repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main
  #     state: present
  #     update_cache: yes
  - name: installing gcloud
    apt:
      pkg:
      - google-cloud-sdk
      - kubectl
      state: present
  # TODO: figure out a way to automate login
