---
- hosts: dev
  vars_files:
  - env_variables
  tasks:
  - name: install go
    become: yes
    shell: |
      curl -L "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz" | tar -C /usr/local -xz
    args:
      creates: /usr/local/go
  - name: create ~/go
    file:
      path: ~/go
      state: directory
  - name: mount gopath over nfs
    become: yes
    shell: |
      mount {{ gopath }} /home/{{ user }}/go
      touch ~/.ansible_checks/mount_gopath
    args:
      creates: ~/.ansible_checks/mount_gopath
  - name: update fstab for gopath mount
    become: yes
    lineinfile:
      path: /etc/fstab
      line: '{{ gopath }}	/home/{{ user }}/go  nfs4	defaults,user,exec  0 0'
      state: present
  - name: add redeam bitbucket git override (line 1)
    lineinfile:
      path: ~/.gitconfig
      line: '[url "git@bitbucket.org:redeam"]'
      state: present
  - name: add redeam bitbucket git override (line 2)
    lineinfile:
      path: ~/.gitconfig
      line: '        insteadOf = https://bitbucket.org/redeam'
      state: present
# FIXME: determine why this line doesn't work but the command itself does
# when issued directly.
#  - name: configure redeam repos as go private
#    shell:
#      /usr/local/go/bin/go env -w GOPRIVATE=bitbucket.org/redeam
#      touch ~/.ansible_checks/redeam_private_repos
#    args:
#      creates: ~/.ansible_checks/redeam_private_repos
