---
- hosts: dev
  vars_files:
  - env_variables
  tasks:
  - name: creating ansible_checks
    file:
      path: ~/.ansible_checks
      state: directory
  - name: creating root/ansible_checks
    become: yes
    file:
      path: ~/.ansible_checks
      state: directory
  - name: install dependencies
    become: yes
    apt:
      pkg: "{{ packages }}"
      state: present
  - name: transfer ownership of var data
    become: yes
    shell: |
      chown -R {{ user }} /var/data
      touch ~/.ansible_checks/claim_data
    args:
      creates: ~/.ansible_checks/claim_data
  - name: create ~/eddy
    file:
      path: ~/eddy
      state: directory
  - name: mount eddy over nfs
    become: yes
    shell: |
      mount {{ eddy }} /home{{ user }}/eddy
      touch ~/.ansible_checks/mount_eddy
    args:
      creates: ~/.ansible_checks/mount_eddy
  - name: update fstab for eddy mount
    become: yes
    lineinfile:
      path: /etc/fstab
      line: '{{ eddy }}	/home{{ user }}/eddy nfs4  defaults,user,exec  0 0'
      state: present
