---
- hosts: nodes
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: add docker apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add docker apt repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release_name }} stable
      state: present
      update_cache: yes
  - name: installing docker
    apt:
      pkg:
      - docker-ce
      state: present
  - name: creating docker group
    group:
      name: docker
      state: present
