---
- hosts: helcar
  vars_files:
  - env_variables
  tasks:
  - name: install go
    become: yes
    shell: |
      curl -L "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz" | tar -C /usr/local -xz
      touch ~/.ansible_checks/install_go
    args:
      creates: ~/.ansible_checks/install_go
  - name: copy shell files
    copy:
      src: ./go.sh
      dest: ~/.go.sh
  - name: update bashrc
    shell: |
      echo '. ~/.go.sh' >> ~/.bashrc
      touch ~/.ansible_checks/go_path
    args:
      creates: ~/.ansible_checks/go_path
  - name: link /depths/go to ~/
    file:
      dest: ~/go
      src: /depths/go
      state: link
