---
- hosts: homelab
  vars_files:
  - env_variables
  tasks:
  - name: add hashicorp apt-key
    become: yes
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present
  - name: add hashicorp apt repository
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ lsb_release_name }} main
      state: present
      update_cache: yes
  - name: installing hashicorp utilities
    become: yes
    apt:
      pkg:
      - terraform
      - packer
      state: present
