---
- hosts: helcar
  become: yes
  tasks:
  - name: installing bridge-utils
    apt:
      pkg:
      - bridge-utils
      state: present
  - name: copy interfaces
    copy:
      src: ./interfaces
      dest: /etc/network/interfaces
  - name: copy br0
    copy:
      src: ./br0
      dest: /etc/network/interfaces.d/br0
  # NOTE: for some reason running this required a manual reboot
  # before I could gain back SSH access.
  - name: starting bridge network
    shell: |
      ifup br0 && touch ~/.ansible_checks/network_manager
    args:
      creates: ~/.ansible_checks/network_manager
