---
# If considering changing this we've added nodes, consider
# swapping storage pools to ceph.
- hosts: helcar
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: install nfs
    apt:
      pkg:
      - nfs-kernel-server
      state: present
  - name: share nfs directories
    lineinfile:
      path: /etc/exports
      line: '{{ item }}  192.168.42.0/24(rw,sync,no_subtree_check)'
      state: present
    with_items: "{{ nfs_shares }}"
  - name: restart nfs server
    shell: |
      systemctl restart nfs-kernel-server
      touch ~/.ansible_checks/nfs_server_restart
    args:
      creates: ~/.ansible_checks/nfs_server_restart
