---
- name: perform client tasks
  import_tasks: ubuntu_client.yml
  when: (is_server is not defined) or (is_server == false)

- name: perform server tasks
  import_tasks: ubuntu_server.yml
  when: is_server == true
