repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
# - name: incubator
  # url: https://kubernetes-charts-incubator.storage.googleapis.co
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: jetstack
  url: https://charts.jetstack.io

helmDefaults:
  # verify the chart before upgrading (only works with packaged charts not directories) (default false)
  # verify: true
  # wait for k8s resources via --wait. (default false)
  # wait: true

releases:
  - name: bootstrap
    chart: "./bootstrap"
    needs:
    - cert-manager/cert-manager
    values:
      - cert_manager_email: ingcr3at1on@gmail.com
      - cloudflare_key: {{ requiredEnv "CLOUDFLARE_API_KEY" }}

  - name: metallb
    namespace: metallb-system
    createNamespace: true
    chart: bitnami/metallb
    version: v0.1.21 # 0.9.3
    values:
      - configInline:
          address-pools:
            name: default
            protocol: layer2
            addresses: {{ requiredEnv "LOAD_BALANCER_IP" }}

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v0.16.1
    values:
      - installCRDs: true
