---
# TODO:
#   figure out how to connect without an ssh key and load my ssh keys
#   disable ssh with passwords
#   configure sudo, this needs to be done before anything else will work properly.
#   edit apt sources, these are mangled for the cd it would appear.
- import_playbook: resources/init.yml
- import_playbook: resources/go.yml
- import_playbook: resources/fancontroller.yml
- import_playbook: resources/hashi.yml
- import_playbook: resources/zfs.yml
- import_playbook: resources/docker.yml
- import_playbook: resources/libvirt.yml
- import_playbook: resources/libvirt_terraform.yml
# NOTE: if this is the first time this is being ran
# applying this will force an IP address change.
- import_playbook: resources/network.yml
- import_playbook: resources/nfs.yml
- import_playbook: resources/shrc.yml
